### PR TITLE
📝 Add perturbation use case changelog details

### PR DESCRIPTION
**Pull request by Zethson**
- Adds more details for new perturbation use case to changelog

### CODE REVIEW

**Comment by Zethson** [comment]
I wasn't sure what you had in mind for more details @falexwolf . Something like this?

**Comment by falexwolf** [comment]
I realize that most recent "Guide" links were prone to breakage. The last correct one was this one

```
/scrna-tiledbsoma.ipynb#update-the-array-store
```

This is the kind of "Guide" link that I'm thinking of that directs users browsing the changelog to the right spot immediately.

**Comment by falexwolf** [comment]
Hence, @Zethson, please replace

[Use case for curating perturbations](https://docs.lamin.ai/perturbation)

with

[Guide](/perturbation)

**Comment by Zethson** [comment]
Already done and I figured it out :) Thanks!

**Comment by falexwolf** [comment]
Thank you!

**Pull request merged**
